### ISSUE TITLE
unittest.TestCase.assertWarns fails with py imported

### ISSUE THREAD

**Issue by kernc** [pytest-dev/py#110]
`unittest.TestCase.assertWarns()` fails with `RuntimeError` when `py` is imported.

This simple unit test:
```py
import unittest
import warnings

import pandas as pd  # imports py.* somewhere deep

class Case(unittest.TestCase):
    def test_assertWarns(self):
        with self.assertWarns(UserWarning):
            warnings.warn('Some warning')
```
when run with:
```bash
python -m unittest example.py
```
fails with:
```
======================================================================
ERROR: test_assertWarns (example.Case)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/example.py", line 9, in test_assertWarns
    with self.assertWarns(UserWarning):
  File "/usr/lib/python3.4/unittest/case.py", line 205, in __enter__
    for v in sys.modules.values():
RuntimeError: dictionary changed size during iteration
----------------------------------------------------------------------
```

While I agree this is a [_unittest_ module issue](https://github.com/pytest-dev/pytest/issues/1288#issuecomment-167364150) (CPython [bug 29620](https://bugs.python.org/issue29620)), I should hope it can be more quickly resolved on the pylib's side.

Ref: https://github.com/pytest-dev/pytest/issues/1288

**Comment by kernc** [comment]
Related CPython issue: https://bugs.python.org/issue29620

**Comment by RonnyPfannschmidt** [comment]
strictly speaking this is an apipkg bug
