### ISSUE TITLE
AssertionError: installation problem: 1.10.0 is too old, remove or upgrade 'py'

### ISSUE THREAD

**Issue by xqliang** [pytest-dev/py#268]
pip environment:
```
Python 2.7
pytest-2.7.3
py-1.10.0
```

Errors:
```
Traceback (most recent call last):
  File ".tox/py27-latest-lib/bin/py.test", line 5, in <module>
    from pytest import main
  File ".tox/py27-latest-lib/local/lib/python2.7/site-packages/pytest.py", line 14, in <module>
    from _pytest.config import main, UsageError, _preloadplugins, cmdline
  File ".tox/py27-latest-lib/local/lib/python2.7/site-packages/_pytest/config.py", line 12, in <module>
    from _pytest.core import PluginManager
  File ".tox/py27-latest-lib/local/lib/python2.7/site-packages/_pytest/core.py", line 11, in <module>
    "%s is too old, remove or upgrade 'py'" % (py.__version__))
AssertionError: installation problem: 1.10.0 is too old, remove or upgrade 'py'
```

Source code:
```python
# ['1', '10'] >= ['1', '4'] return false, should change to numeric compare: [1, 10] >= [1, 4]
assert py.__version__.split(".")[:2] >= ['1', '4'], ("installation problem: "
    "%s is too old, remove or upgrade 'py'" % (py.__version__))
```

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/b4c47c0ac0699da6c604231f07369e527f1d33cd/_pytest/core.py doesn't even exist in current pytest

pytest 3.0 pretty much removed the line in question almost 5 years ago
